# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

variables:
- group: tf_new_project_variables


stages:
- stage: Validate
  displayName: Validate and Publish artifact
  jobs:
  - job: tfValidate
    pool:
      vmImage: windows-latest
    steps:

    - task: Terraform@2
      inputs:
        TemplatePath: './ado_project'
        Arguments: 'init'
        InstallTerraform: true
        UseAzureSub: false
    - task: Terraform@2
      inputs:
        TemplatePath: './ado_project'
        Arguments: 'validate'
        InstallTerraform: true
        UseAzureSub: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: './ado_project'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: TerraformFilesDrop
      inputs:
        ArtifactName: TerraformFiles
        PathtoPublish: $(Build.ArtifactStagingDirectory)