# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'vsts-vmdime'
#pool: 'NubiralAgentPools'

variables:
- group: iac_acr_variables
- group: iac_aks_cluster_variables
- group: iac_aks_rg_variables
- group: iac_aks_sa_crb_variables
- group: iac_aks_sp_variables
- group: iac_aks_subnet_variables
- group: iac_aks_vnet_variables
- group: iac_nginx_helm_variables
- group: IaC_sp_variables
- group: IaC_tfstate_Variables

stages:
- stage: Validate
  displayName: Validate and Publish artifact
  jobs:
  - job: tfValidate
    pool: 'vsts-vmdime'
    #pool: 'NubiralAgentPools'
    steps:

    - task: replacetokens@3
      inputs:
        rootDirectory: 'AKS_IaC'
        targetFiles: '**/provider.tf'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTransforms: false
        enableTelemetry: true

    - task: Terraform@2
      inputs:
        TemplatePath: './AKS_IaC/'
        Arguments: 'init'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Automation SPN'
        ManageState: false
    - task: Terraform@2
      inputs:
        TemplatePath: './AKS_IaC/'
        Arguments: 'validate'
        InstallTerraform: true
        UseAzureSub: true
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Automation SPN'
        ManageState: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: './AKS_IaC/'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: TerraformFilesDrop
      inputs:
        ArtifactName: TerraformFiles
        PathtoPublish: $(Build.ArtifactStagingDirectory)